version: 2
jobs:
  deploy:
    working_directory: ~/experiment
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout
      - run: 
          command: |
            sudo apt-get -y update && sudo apt-get -y install rsync
            ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts
            rsync -a --delete ~/experiment/ $VM_USER@$VM_IP:/home/$VM_USER/experiment
            ssh -oStrictHostKeyChecking=no -v $VM_USER@$VM_IP "
              echo $PATH;
              echo $(pwd);
              echo $(go help);
              cd /home/$VM_USER/experiment;
              go build main.go;
              ./main;
            "

workflows:
  version: 2
  deploy-to-vps:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

