version: 2
jobs:
  build:
    docker:
      
      - image: circleci/golang:1.9

    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $VM_USER@$VM_IP "cd CI-CD-Experiment && ./run.sh"