version: 2
jobs:
  deploy:
    working_directory: ~/experiment
    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout
      - run: 
          command: |
            sudo apt-get -y update && sudo apt-get -y install rsync
            rsync -a --delete ~/experiment/ $VM_USER@$VM_IP:/home/$VM_USER/experiment
            ssh $VM_USER@$VM_IP
            cd /home/$VM_USER/experiment
            ./run.sh

workflows:
  version: 2
  deploy-to-vps:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

